version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - gh-action
    schedule:
      interval: daily
