changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change
    - title: 🏕 Improvements/Enhancements
      labels:
        - enhancement
    - title: 🛠 Bug Fixes
      labels:
        - bug
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 📚 Other Changes 
      labels:
        - "*"
