archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_v
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - '{{ .ProjectName }}_v{{ .Version }}_SHA256SUM.txt'
before:
  hooks:
    - go mod tidy
builds:
  - binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    main: './src/cmd/{{ .ProjectName }}/main.go'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/manhtukhang/{{ .ProjectName }}.Version=v{{ .Version }}'
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post: |-
        sh -c "
          cd dist/{{ .ProjectName }}_{{ .Target }} &&\
          sha256sum {{ .ProjectName }}_v{{ .Version }}* > ../../{{ .ProjectName }}_v{{ .Version }}_SHA256SUM.txt
        "
sboms:
  - id: spdx
    artifacts: archive
checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS.txt'
changelog:
  use: github-native
release:
  draft: true
  replace_existing_draft: true
