name: First interaction

on:
  pull_request:
    branches:
      - main
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greetings for PR and issues
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue!!'
        pr-message: 'Hello @${{ github.actor }} , thank you for submitting a pull request!!'
