name: Security scanning
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  security:
    if: github.repository == 'manhtukhang/vault-plugin-secrets-nexus-repository'
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/golang@cdb760004ba9ea4d525f2e043745dfe85bb9077e # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # To make sure that SARIF upload gets called
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3.27.5
        with:
          sarif_file: snyk.sarif
