name: Acceptance Test

on:
  push:
    tags-ignore: '**'
  pull_request:


permissions:
  contents: read

jobs:
  pre_job:
    # continue-on-error: true
    permissions:
      actions: write # for fkirc/skip-duplicate-actions to skip or stop workflow runs
      contents: read # for fkirc/skip-duplicate-actions to read and compare commits
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          paths: '["go.mod", "go.sum", "Makefile", "src/**/*", "test/**/*"]'

  build:
    name: Build plugin executable binary
    needs: pre_job
    runs-on: ubuntu-latest
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Build plugin
        id: build-plugin
        run: make build

      - name: Upload plugin
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: vault-plugin-secrets-nexus-repository
          path: dist/bin
          if-no-files-found: error
  test:
    permissions:
      contents: write
    needs: [ pre_job, build ]
    strategy:
      matrix:
        vault: [ "1.17.6", "1.18.2" ]
        nexus: [ "3.73.0", "3.74.0" ]
    uses: ./.github/workflows/_test-acceptance.tmpl.yaml
    with:
      vault-version: ${{ matrix.vault }}
      nxr-version: ${{ matrix.nexus }}
      vault-plugin-dir: ./dist/bin
